# Generated by Django 6.1 on 2026-08-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberResource',
        ),
    ]
