# Generated by Django 6.1 on 2026-08-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0002_delete_memberresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberAnnouncement',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='suspended_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
