# Generated by Django 6.1 on 2026-08-18 06:36

import sboi.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0003_delete_memberannouncement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='image',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='devotions/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='events/'),
        ),
    ]
