# Generated by Django 6.1 on 2026-08-18 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0004_alter_announcement_image_alter_announcement_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
