# Generated by Django 6.1 on 2026-08-18 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0005_alter_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pdfmaterial',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='pdfmaterial',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
