# Generated by Django 6.1 on 2026-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboard', '0006_alter_devotion_date_alter_devotion_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmaterial',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
