# Generated by Django 6.1 on 2026-08-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(help_text='Recommended size: 1920x1080 (16:9).', upload_to='slider/'),
        ),
    ]
