# Generated by Django 6.1 on 2026-08-18 07:50

import sboi.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=sboi.fields.OptimizedImageField(blank=True, help_text='Recommended size: 1920x1080 (16:9).', upload_to='slider/'),
        ),
    ]
