# Generated by Django 6.1 on 2026-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
