# Generated by Django 6.1 on 2026-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_sliderimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='placement',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('gallery', 'Gallery'), ('both', 'Both')], default='home', max_length=10),
        ),
    ]
