# Generated by Django 6.1 on 2026-08-18 07:50

import sboi.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredsection',
            name='image',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='home/sections/'),
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
