# Generated by Django 6.1 on 2026-08-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_featuredsection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredsection',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
