"""
Django settings for sboi project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qv&sk8dv*%&4x$u-&4wqt$c(oik5e=smc(4+b&4i^0-^+q!cgt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', 'shekinahblaze.org', 'www.shekinahblaze.org', '.onrender.com']

# Admin URL — production overrides this with a secret path (see .env.example).
ADMIN_URL = 'admin/'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'about',
    'blackboard',
    'contact',
    'gallery',
    'members',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sboi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.site_info',
                'home.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'sboi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'members:login'
LOGIN_REDIRECT_URL = 'blackboard:blackboard'
LOGOUT_REDIRECT_URL = 'home:home'


# Jazzmin — premium admin theme
JAZZMIN_SETTINGS = {
    'site_title': 'Shekinah Blaze Admin',
    'site_header': 'Shekinah Blaze Outreach International',
    'site_brand': 'Shekinah Blaze',
    'site_logo': 'images/home/Logo.png.png',
    'site_logo_classes': 'img-fluid',
    'welcome_sign': 'Governed by Heaven, Established on Earth',
    'copyright': 'Shekinah Blaze Outreach International',
    'search_model': ['auth.User', 'blackboard.Devotion', 'blackboard.Sermon', 'blackboard.Event'],
    'topmenu_links': [
        {'name': 'View Website', 'url': '/', 'new_window': False, 'icon': 'fas fa-globe'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': ['home', 'about', 'blackboard', 'gallery', 'contact', 'auth'],
    'custom_css': 'admin/css/admin-brand.css',
    'custom_js': None,
    'show_ui_builder': False,
    'language_chooser': False,
    'icons': {
        'auth.Group': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'home.HomeStat': 'fas fa-chart-line',
        'home.FeaturedSection': 'fas fa-star',
        'home.Testimony': 'fas fa-comment-dots',
        'home.Subscriber': 'fas fa-envelope-open-text',
        'about.ChurchProfile': 'fas fa-church',
        'about.CoreValue': 'fas fa-gem',
        'about.Leader': 'fas fa-user-tie',
        'about.MissionAction': 'fas fa-hands-helping',
        'about.MissionComponent': 'fas fa-bullseye',
        'about.PathwayStep': 'fas fa-route',
        'about.VisionPillar': 'fas fa-eye',
        'blackboard.Announcement': 'fas fa-bullhorn',
        'blackboard.Devotion': 'fas fa-book-open',
        'blackboard.Event': 'fas fa-calendar-days',
        'blackboard.EventRsvp': 'fas fa-clipboard-check',
        'blackboard.MemberProfile': 'fas fa-id-card',
        'blackboard.PdfMaterial': 'fas fa-file-pdf',
        'blackboard.Sermon': 'fas fa-video',
        'contact.ContactInfo': 'fas fa-address-book',
        'contact.ContactMessage': 'fas fa-envelope',
        'gallery.SliderImage': 'fas fa-images',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
}

JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'default_theme_mode': 'light',
    'light_theme': 'flatly',
    'dark_theme': 'slate',
    'navbar': 'navbar-dark navbar-primary',
    'sidebar': 'sidebar-dark-primary',
    'no_navbar_border': True,
    'navbar_small_text': False,
    'sidebar_small_text': True,
    'body_small_text': False,
    'brand_colour': 'navbar-primary',
    'accent': 'accent-primary',
    'footer_fixed': False,
    'navbar_fixed': True,
    'sidebar_fixed': True,
}

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

CSRF_FAILURE_VIEW = 'sboi.views.csrf_failure'
