# Generated by Django 6.1 on 2026-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Shekinah Blaze Outreach International', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('founder_name', models.CharField(blank=True, max_length=200)),
                ('founder_role', models.CharField(blank=True, max_length=200)),
                ('founder_scripture', models.CharField(blank=True, max_length=300)),
                ('founder_message', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('story_image', models.ImageField(blank=True, upload_to='about/')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision', models.TextField(blank=True)),
                ('vision_scripture', models.CharField(blank=True, max_length=300)),
                ('vision_declaration', models.TextField(blank=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission', models.TextField(blank=True)),
                ('mission_scripture', models.CharField(blank=True, max_length=300)),
                ('mission_declaration', models.TextField(blank=True)),
                ('culture_statement', models.TextField(blank=True)),
                ('values_declaration', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Church Profile',
                'verbose_name_plural': 'Church Profile',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('scripture', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='about/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PathwayStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisionPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
