# Generated by Django 6.1 on 2026-08-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corevalue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='missioncomponent',
            name='body',
        ),
        migrations.RemoveField(
            model_name='visionpillar',
            name='body',
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_commitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_multiplication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='vision_future',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='vision_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='vision_practice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='our_commitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='what_this_means',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='what_we_believe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missioncomponent',
            name='belief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missioncomponent',
            name='commitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missioncomponent',
            name='practice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='missioncomponent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visionpillar',
            name='belief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visionpillar',
            name='commitment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visionpillar',
            name='practice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visionpillar',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
