# Generated by Django 6.1 on 2026-08-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_corevalue_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missioncomponent',
            old_name='belief',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='visionpillar',
            old_name='belief',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='missioncomponent',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='missioncomponent',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='visionpillar',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='visionpillar',
            name='practice',
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_components_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_in_action_closing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='mission_key_scripture',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='pathway_closing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='pathway_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='values_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='vision_components_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='vision_key_scripture',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
