# Generated by Django 6.1 on 2026-08-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_remove_missioncomponent_belief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchprofile',
            name='mission_in_action_intro',
            field=models.TextField(blank=True),
        ),
    ]
