# Generated by Django 6.1 on 2026-08-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_churchprofile_mission_in_action_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchprofile',
            name='founder_byline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='founder_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='founder_tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='churchprofile',
            name='story_subtitle',
            field=models.TextField(blank=True),
        ),
    ]
