# Generated by Django 6.1 on 2026-08-18 07:50

import sboi.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_churchprofile_founder_byline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchprofile',
            name='story_image',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='leader',
            name='photo',
            field=sboi.fields.OptimizedImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='missionaction',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='missioncomponent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pathwaystep',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='visionpillar',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
