# Generated by Django 6.1 on 2026-08-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_corevalue_order_alter_leader_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaystep',
            name='step',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
